//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NameMyFee
{
    using System;
    using System.Collections.Generic;
    
    public partial class invitee
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string bid_amount { get; set; }
        public string document_name { get; set; }
        public byte[] document { get; set; }
        public string uni_name { get; set; }
        public string program { get; set; }
        public Nullable<int> application_id { get; set; }
    }
}
